# this support npm-gulp.yml file is used to run the npm-gulp.yml file in the root of the repository
name: Support npm-gulp.yml
on:
  workflow_run:
    workflows: ["npm-gulp.yml"]
    types:
      - completed
jobs:
  support:
    runs-on: ubuntu-latest

    steps:
    - name: Check if npm-gulp.yml completed successfully
      run: |
        if [ "${{ github.event.workflow_run.conclusion }}" != "success" ]; then
          echo "npm-gulp.yml did not complete successfully. Skipping support tasks."
          exit 1
        fi

    - name: Run support tasks
      run: |
        echo "Running support tasks for npm-gulp.yml..."
        # Add any additional support tasks here
        echo "Support tasks completed successfully."
    - name: Notify on support completion
      run: echo "Support tasks for npm-gulp.yml completed successfully."
    - name: Notify on support failure
      if: failure()
      run: echo "Support tasks for npm-gulp.yml failed. Please check the logs for details."
    - name: Post support cleanup
      if: always()
      run: |
        echo "Cleaning up support tasks..."
        # Add any cleanup commands here
        echo "Support tasks cleanup completed."
    - name: Upload support logs